- binding.gyp
- lib/index.js
- package.json
- src/errable.cpp
- src/errable.h
- src/lock.cpp
- src/lock.h
- src/log.cpp
- src/main.cpp
- src/message.h
- src/queue.cpp
- src/queue.h
- src/result.h
- src/status.cpp
- src/status.h
- src/thread.cpp
- src/thread.h
- src/worker/linux/linux_worker_platform.cpp
- src/worker/macos/macos_worker_platform.cpp
- src/worker/windows/windows_worker_platform.cpp
- src/worker/worker_platform.h
- src/worker/worker_thread.cpp
- src/worker/worker_thread.h
- test/watcher.js
Improve the error reporting mechanism.
> Improve error reporting

- src/main.cpp
- test/watcher.js
Allow users to disable logging by passing `null` to the configure function.
This is necessary for the tests to work properly on Windows. Otherwise, the worker thread prevents the `afterEach()` hook from being able to clean up its fixture directory properly.
> Disable logging

- binding.gyp
- package.json
- src/helper/linux/helper.h
- src/message_buffer.cpp
- src/message_buffer.h
- src/result.h
- src/worker/linux/cookie_jar.cpp
- src/worker/linux/cookie_jar.h
- src/worker/linux/linux_worker_platform.cpp
- src/worker/linux/pipe.h
- src/worker/linux/side_effect.cpp
- src/worker/linux/side_effect.h
- src/worker/linux/watch_registry.cpp
- src/worker/linux/watch_registry.h
- src/worker/linux/watched_directory.cpp
- src/worker/linux/watched_directory.h
- test/watcher.js
> Use inotify to watch directories on Linux.

- src/worker/macos/event_handler.cpp
- src/worker/macos/macos_worker_platform.cpp
- test/watcher.js
MacOS can't handle a collapsed creation and rename event for an entry that's no longer present, because there's no inode to use to correlate it to a corresponding destination rename event (if there is one). Delay the rename event in the failing spec until after the creation event arrives to tease apart the events and give the MacOS platform-specific code a chance to see and handle it.
> Change test case for renames out of the watched root

- src/worker/macos/macos_worker_platform.cpp
- src/worker/macos/recent_file_cache.cpp
- src/worker/macos/recent_file_cache.h
The MacOS watcher thread uses a recent file cache of stat results to associate the halves of rename events, but it's unable to detect renames from files and directories that existed before the watcher was started. Pre-populate the cache with a bounded number of stat() results (currently 4096) discovered by a breadth-first traversal.
> Prepopulate the recent file cache on MacOS

- circle.yml
- src/helper/windows/helper.h
- src/worker/windows/windows_worker_platform.cpp
Windows' `GetLastError()` appends a `.<CRLF>` to every error message, which looks ugly in the logs. Manually clean it up a little.
> Report Windows errors in a more friendly way

- src/worker/windows/subscription.cpp
- src/worker/windows/subscription.h
- src/worker/windows/windows_worker_platform.cpp
I wasn't actually able to make this fail with a Samba mount from my Linux machine, so I'm kind of trusting the documentation here.
> Revert to polling when a Windows filesystem does not support the change API

- lib/index.js
- src/message.cpp
- src/message.h
- src/message_buffer.h
- src/polling/polled_root.cpp
- src/polling/polled_root.h
- src/polling/polling_iterator.cpp
- src/polling/polling_thread.cpp
- src/polling/polling_thread.h
- src/worker/linux/linux_worker_platform.cpp
- src/worker/linux/side_effect.cpp
- src/worker/linux/side_effect.h
- src/worker/linux/watch_registry.cpp
- src/worker/linux/watch_registry.h
Automatically fall back to polling when inotify runs out of watch descriptors.
This is trickier than the Windows and MacOS implementations because a single ADD command can _partially_ succeed in inotify-land. This means that an ADD sent to the worker thread could need to send multiple ADDs to the polling thread, and the AckMessage should only be produced once all of the polling ADDs have done their initial scan.
Fixes #5.
> Linux polling fallback

- src/hub.h
- src/polling/directory_record.cpp
Fix a few issues I noticed while I'm on the Windows box:
* A crash in the polling thread tests when built in debug mode
* Disable means disable, not "actually log to stderr" kthx
> Windows fixes

- .travis.yml
Travis doesn't cache apt installations, and as a consequence, LLVM has [throttled connections from cloud hosting providers](http://lists.llvm.org/pipermail/llvm-dev/2017-May/113269.html).
We're already linting and format-checking on Circle CI, so let's just disable the clang-5.0 checks on Travis for now.
> Don't lint or format C++ on Travis

- lib/path-watcher.js
- src/worker/macos/batch_handler.cpp
- src/worker/macos/recent_file_cache.cpp
- src/worker/macos/recent_file_cache.h
- src/worker/macos/rename_buffer.cpp
- src/worker/macos/rename_buffer.h
- test/index.test.js
- test/matcher.js
When called with the name of a single file, create a non-recursive `PathWatcher` on its parent directory that only reports events that pertain to that file's path.
> Watch a single file

- lib/binding.js
- package-lock.json
- package.json
Directly exporting symbols required from the native bindings makes electron-link unhappy. Make _those_ functions defer use of the native bindings to make the whole thing snapshottable.
> Lazily require native bindings

- src/errable.cpp
- src/errable.h
- src/hub.cpp
- src/hub.h
- src/polling/polling_thread.cpp
- src/queue.cpp
- src/queue.h
- src/status.h
- src/thread.cpp
- src/thread.h
- src/worker/linux/linux_worker_platform.cpp
- src/worker/linux/pipe.cpp
- src/worker/linux/pipe.h
- src/worker/linux/watch_registry.cpp
- src/worker/macos/macos_worker_platform.cpp
- src/worker/windows/windows_worker_platform.cpp
- src/worker/worker_platform.h
- src/worker/worker_thread.cpp
SyncErrable is a relic of the synchronous `.status()` call. Because I needed to be able to read thread and queue Errable states from the main thread and the other threads, I had to synchronize access to the errored state of each resource, which is really expensive. Now that `.status()` is async from #79, I can cut out SyncErrable and simplify its interface a great deal.
I've also taken advantage of the fact that Errable states were _only_ being set within constructors. There's no reason to check `is_healthy()` in every single method if I can do it once after construction.
> Remove SyncErrable

- src/worker/macos/rename_buffer.cpp
- src/worker/macos/rename_buffer.h
When correlating renames, it's possible for the prior entry to be "absent" even if the file was observed previously, due to cache expiration or issues like #88. In this case, we shouldn't emit a "create" event for the rename source. Disambiguate by checking for the presence of `kFSEventStreamEventFlagItemCreated`.
> Check the creation flag when emitting a create/delete pair

- src/worker/macos/recent_file_cache.cpp
- src/worker/macos/recent_file_cache.h
- src/worker/macos/rename_buffer.cpp
- src/worker/macos/rename_buffer.h
- test/events/parent-rename.test.js
- test/events/rapid.test.js
On MacOS, update cached entries within a directory when the directory is renamed. Fixes #88.
> Update cache entries when a parent directory is renamed

- src/polling/directory_record.cpp
- src/polling/directory_record.h
- test/events/root-rename.test.js
If the root directory itself is renamed, emit a single `"deleted"` event for the old path and cease event delivery.
> Handle rename of the watched root directory

- src/worker/macos/batch_handler.cpp
- src/worker/macos/batch_handler.h
- src/worker/macos/macos_worker_platform.cpp
- src/worker/macos/rename_buffer.cpp
- src/worker/macos/rename_buffer.h
- test/events/parent-rename.test.js
A continuation of the work from #90, because spurious events are still being generated in watcher-stress.
The case that's causing the most problems is when:
1. A file `/root/parent-0/child-0.txt` is renamed to `/root/parent-0/child-1.txt`.
2. The parent directory `/root/parent-0` is renamed to `/root/parent-1`.
3. A single event batch containing both events is received by the watcher after both operations complete.
When the rename event for `child-0.txt` is processed, the `lstat()` call fails, because its path is no longer valid and we haven't seen the directory rename yet. This triggers the "absent :point_right: absent" case in the RenameBuffer, which infers a spurious deletion event.
> Additional parent directory rename cases

- test/events/nonrecursive.test.js
- test/events/parent-rename.test.js
It passes for me here, even with 100 iterations. I forget why it was disabled to begin with?
> Enable the last nonrecursive watcher test on Windows

- src/worker/windows/subscription.cpp
- src/worker/windows/subscription.h
- src/worker/windows/windows_worker_platform.cpp
- test/events/kind-change.test.js
Associate renames that are split across event batches on Windows by storing the old path in the subscription.
Fixes #84, at least partially.
> Correlated renames split across batches on Windows

- src/worker/windows/windows_worker_platform.cpp
Windows reports `FILE_ACTION_MODIFIED` for directories for a wide variety of actions, including things like modification of a containing file (which technically changes the last-access timestamp on the directory). These aren't useful, so let's just skip them.
> Skip directory modification events on Windows

- src/helper/windows/helper.cpp
- src/helper/windows/helper.h
- src/worker/recent_file_cache.cpp
- src/worker/windows/windows_worker_platform.cpp
- test/events/basic.test.js
- test/events/rapid.test.js
Convert all path names to long path names whenever possible.
Fixes #85.
> Consistently report long path names on Windows

- src/worker/windows/subscription.cpp
1MB is overkill for the buffer size.  Batch processing is pretty quick because the worker thread just stats and enqueues all of the events.
Fixes #69.
> Drop the buffer size to 128K

- lib/registry/helper.js
- lib/registry/tree.js
- src/message.cpp
- src/worker/macos/macos_worker_platform.cpp
- src/worker/recent_file_cache.cpp
- src/worker/recent_file_cache.h
- src/worker/windows/windows_worker_platform.cpp
- src/worker/worker_thread.cpp
- test/errors.test.js
- test/helper.js
- test/index.test.js
- test/native-watcher-registry.test.js
- test/polling.test.js
- test/unwatching.test.js
- test/watching.test.js
Some non-specific cleanup work I did trying to tackle the root rename problem on Windows.
> Windows miscellany

- package.json
- src/worker/linux/linux_worker_platform.cpp
- src/worker/linux/side_effect.cpp
- src/worker/linux/side_effect.h
- src/worker/linux/watch_registry.cpp
- src/worker/linux/watch_registry.h
- src/worker/linux/watched_directory.cpp
- src/worker/linux/watched_directory.h
- test/events/parent-rename.test.js
Get the test cases introduced by #90 and #92 passing on Linux. These will ensure that we report absolute paths correctly when a parent directory has been renamed.
> Track parent path renames on Linux

- src/worker/linux/side_effect.cpp
- src/worker/linux/side_effect.h
- src/worker/linux/watch_registry.cpp
- src/worker/linux/watched_directory.cpp
- src/worker/linux/watched_directory.h
- test/events/root-rename.test.js
inotify watch descriptors actually follow directories that are renamed, but unless you're watching the parent directory as well, you have no way to know where they're renamed _to_ (and therefore construct absolute paths for events received within them).
Fortunately, inotify has dedicated event flags (`IN_MOVE_SELF` and `IN_DELETE_SELF`) that signal operations performed on the watched directory itself. This makes it pretty easy to synthesize a deletion event and clean up the now-defunct descriptors.
> Rename or deletion of watch root on Linux

- lib/path-watcher.js
- test/events/symlink.test.js
When a directory is watched through a root path that contains a symlink, report event paths to consumers in terms of that symlink. Watchers should still use the real path for native watcher consolidation.
This is the next bit of #19.
> Report paths consistently with watcher creation

- src/helper/windows/helper.cpp
- test/events/unicode-paths.test.js
Test a watch root and event path that includes [four-byte utf8 characters](http://www.i18nguy.com/unicode/supplementary-test.html).
Fixes #12.
> Include a test case that exercises utf8 paths

- src/worker/windows/windows_worker_platform.cpp
When you disconnect a Samba share, a watcher on a directory within it will report an empty event batch.
Fixes #118.
> Accept zero-size event batches from ReadDirectoryChangeW

- src/thread.cpp
- src/thread.h
- src/worker/macos/macos_worker_platform.cpp
- src/worker/windows/windows_worker_platform.cpp
- src/worker/worker_platform.h
- src/worker/worker_thread.cpp
- src/worker/worker_thread.h
If any commands are enqueued for the worker thread before the first call to `MacOSWorkerPlatform::listen()`, some of the state that's necessary for the `handle_xyz_command()` methods hasn't had a chance to be configured yet. Adding an `init()` phase that's guaranteed to be called before the first handle method should help this.
Part of #120.
> Initialize threads before the first handle_commands() call

- package-lock.json
- package.json
- src/binding.cpp
- src/hub.cpp
- src/log.cpp
- src/log.h
- src/polling/polling_thread.cpp
- src/polling/polling_thread.h
- src/thread.cpp
- src/thread_starter.cpp
- src/thread_starter.h
- src/worker/worker_thread.cpp
The existing logging is not helpful enough to be able to diagnose issues that happen during initialization. For `configure()` to be able to communicate with the worker and poller threads to set up logging in the first place, the target thread needs to be running and processing commands - so if it never has a chance to get that far, it's difficult to figure out what's going on.
Setting `WATCHER_LOG_MAIN`, `WATCHER_LOG_WORKER`, or `WATCHER_LOG_POLLING` to either `"stdout"`, `"stderr"`, or the path to a file will configure the logger for the appropriate thread at the earliest possible moment.
> Enable early logging with environment variables

- src/worker/linux/cookie_jar.cpp
- src/worker/linux/cookie_jar.h
- src/worker/linux/linux_worker_platform.cpp
- src/worker/linux/watch_registry.cpp
- src/worker/macos/macos_worker_platform.cpp
- src/worker/macos/rename_buffer.cpp
- src/worker/macos/rename_buffer.h
- test/events/unpaired-rename.test.js
When synthesizing deletion events for unpaired renames on MacOS, be sure to evict the file from the cache.
Fixes #117.
> Evict cache entries for expired rename moves

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
This PR adds `node-pre-gyp` (https://github.com/mapbox/node-pre-gyp) to handle binary packaging and publishing. I tested `npm install` and `npm run publish` with my AWS creds for the `atom-watcher-test` S3 bucket I created and it all worked as expected.
A couple things will need to be handled by the maintainers of this package:
1. We'll need an S3 bucket for the binaries.
2. Upload creds for said bucket will need to be added to the CI tools.
3. A method of releasing builds will need to be decided. Common practices that I've seen:
- Publish when a specific token exists in the commit message, ie `[ci-publish]`
- Publish when a git tag is pushed
What `node-pre-gyp` does could be manually handled, but it seems `node-pre-gyp` is pretty well established and worked for me with minimal …
> Add node-pre-gyp to publish binaries

- package-lock.json
- src/helper/macos/helper.h
- src/message.cpp
- src/message.h
- src/worker/macos/macos_worker_platform.cpp
`clang-tidy` has added a few new checks since the last time I touched this, so builds are failing. Let's clean the new findings up.
> Linter updates

- .travis.yml
- README.md
Test with node 8 instead of node 7 on travis. I think that atom comes with electron 2.0 now, and it is a node 8 that is packaged with it, so it'd be safer to also test with node 8 on travis.
> Test with node 8 on travis

- .circleci/config.yml
- src/log.cpp
... because I misplaced a `return` statement. Oops.
Hopefully this will get our CI working again too 🤞 
Fixes #170.
> Fix logging

- README.md
- lib/binding.js
- lib/logger.js
- lib/native-watcher-registry.js
- lib/native-watcher.js
- lib/path-watcher.js
- lib/registry/tree.js
- package-lock.json
I'm trying to track down #124, and I _suspect_ it's a race condition within the JavaScript-level NativeRegistryTree. The existing logging isn't helpful here because the process seems to lock before `binding.watch` is called. I'm adding a bunch of logging through the JavaScript layer, controlled by `WATCHER_LOG_JS`.
> JavaScript-level logging

- src/binding.cpp
- src/hub.cpp
- src/nan/all_callback.cpp
- src/nan/all_callback.h
- src/worker/worker_thread.cpp
- src/worker/worker_thread.h
- test/configuration.test.js
Defer the worker thread start until at least one watch root is added. We already have similar logic in place to start and stop the polling thread.
This should address #185, although I'll have to tag a prerelease to be sure.
> Defer worker start

- src/binding.cpp
- src/hub.cpp
- src/hub.h
It looks like `uv_async_init()` prevents Node's event loop from exiting cleanly, even with the worker thread not launched yet. Defer constructing the `Hub` singleton until the first time it's interacted with to prevent that call from being performed immediately on module require.
Another take on #185.
> Construct Hub lazily

- package-lock.json
- package.json
- src/binding.cpp
- src/hub.cpp
- src/nan/all_callback.cpp
- src/nan/all_callback.h
- src/worker/worker_thread.cpp
- src/worker/worker_thread.h
- test/configuration.test.js
#201 is what ultimately fixed the prebuild hang issue. I'm getting some test failures and renderer crashes on atom/atom#17899 with 1.3.0, and this is the riskiest change that went in to that release, so I'm going to revert and see if that improves things.
Reverts atom/watcher#200.
> Revert "Defer worker start"

- .circleci/config.yml
- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
- src/message.cpp
- src/message.h
- src/polling/directory_record.cpp
- src/polling/polled_root.cpp
- src/polling/polling_iterator.cpp
- src/polling/polling_thread.cpp
- src/worker/linux/cookie_jar.cpp
- src/worker/linux/watched_directory.cpp
- src/worker/macos/batch_handler.cpp
- src/worker/macos/rename_buffer.cpp
- src/worker/macos/subscription.cpp
- src/worker/recent_file_cache.cpp
- src/worker/worker_thread.cpp
- Update all CI config files to support node 12
- Updated xcode version to unblock ci (8.3.3 has been deprecated)
- Bump nan dependency
- Run format C++
- Disabled C++ Lint task for now, due to ~200 warnings-as-errors resulted from the mandatory xcode upgrade
> Add Node 12 Support
