atom/watcher

.travis.yml
README.md
circle.yml
package-lock.json
package.json

Hopefully help us dodge some of the macOS queue capacity issues on Travis, and give us a nice, clean separation of our three major platforms in our README badges.
Fixes #1.

Move the macOS build to CircleCI

---

.travis.yml
binding.gyp
package.json
src/main.cpp
src/worker/linux/linux_worker_platform.cpp
src/worker/windows/windows_worker_platform.cpp
test/sfw.js

Let's get green tests on AppVeyor and Travis by stubbing out the test cases I haven't gotten to yet on those platforms.

Stub out Windows and Linux platform implementations

---

src/worker/windows/windows_worker_platform.cpp
test/watcher.js

Implement the command channel on Windows with `QueueUserAPC`. Fixes #7.

Windows command channel

---

src/worker/windows/windows_worker_platform.cpp

Use `GetLastError()` to report error codes and error text from failed Win32 API calls.

Report errors from the Win32 API

---

appveyor.yml
binding.gyp
lib/index.js
package-lock.json
package.json
src/errable.h
src/helper/windows/helper.cpp
src/helper/windows/helper.h
src/main.cpp
src/message.cpp
src/result.h
src/worker/linux/linux_worker_platform.cpp
src/worker/macos/macos_worker_platform.cpp
src/worker/windows/subscription.cpp
src/worker/windows/subscription.h
src/worker/windows/windows_worker_platform.cpp
src/worker/worker_platform.h
src/worker/worker_thread.cpp
test/watcher.js

Dispatch Windows events with ReadDirectoryChangesW

---

binding.gyp
src/errable.h
src/helper/linux/helper.h
src/worker/linux/linux_worker_platform.cpp
src/worker/linux/pipe.cpp
src/worker/linux/pipe.h
test/watcher.js

Implement a command channel on Linux by using `poll()` with a pipe.
Fixes #8.

Linux command channel

---

src/worker/macos/event_handler.cpp
src/worker/macos/recent_file_cache.cpp
src/worker/macos/recent_file_cache.h
test/watcher.js

Final green spec on MacOS

---

lib/index.js
src/main.cpp
src/message.cpp
src/message.h
src/message_buffer.cpp
src/message_buffer.h
src/worker/macos/event_handler.cpp
src/worker/windows/windows_worker_platform.cpp
test/events.test.js
test/unwatching.test.js
test/watching.test.js

Change the event spec to be consistent with Atom's watchPath events

---

src/message_buffer.h
src/worker/macos/event_handler.cpp
src/worker/macos/event_handler.h
src/worker/macos/macos_worker_platform.cpp
src/worker/macos/rename_buffer.cpp
src/worker/macos/rename_buffer.h

A bit of refactoring for consistency.

Use a ChannelMessageBuffer in the MacOS worker thread

---

test/events.test.js

Fix the final regressing test on Windows.

Windows doesn't provide a kind on deletion events

---

src/hub.cpp
src/thread.cpp
src/worker/macos/macos_worker_platform.cpp

The next part of #5 for MacOS.

Fall back to polling if native watchers fail

---

package-lock.json
package.json
test/configuration.test.js
test/events.test.js
test/helper.js
test/polling.test.js
test/unwatching.test.js
test/watching.test.js

Let's see if I can track down those test flakes on Circle. If not, I'll at least activate mocha-stress.

Use mocha-stress

---

binding.gyp
circle.yml
script/helper/gen-compilation-db.js
src/helper/macos/helper.cpp
src/helper/macos/helper.h
src/worker/macos/event_handler.cpp
src/worker/macos/event_handler.h
src/worker/macos/flags.h
src/worker/macos/macos_worker_platform.cpp
src/worker/macos/recent_file_cache.cpp
src/worker/macos/recent_file_cache.h
src/worker/macos/rename_buffer.cpp
src/worker/macos/rename_buffer.h
src/worker/worker_platform.h
test/events.test.js

Investigate and hopefully correct #50.

Stress-test the flaking test on Circle

---

lib/index.js
lib/path-watcher-manager.js

This will be handy for diagnostics.

Export an accessor to get the NativeRegistry

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
SUPPORT.md

Add all the appropriate templates

---

src/worker/windows/windows_worker_platform.cpp
test/events/rapid.test.js

I can't reproduce it locally in 1000 trials, likely because I have an SSD. I _think_ I see what's going on in CI, though.
Fixes #59.

Improve robustness of flaking Windows test

---

lib/binding.js
src/binding.cpp
src/hub.cpp
src/hub.h
src/log.cpp
src/log.h
src/nan/all_callback.cpp
src/nan/all_callback.h
src/thread.cpp
test/configuration.test.js

Reject the configure() promise when logging to a bad path

---

circle.yml
src/helper/macos/helper.cpp
src/helper/macos/helper.h
src/worker/macos/batch_handler.cpp

Necessary to get atom/atom#16124 green.

Build on XCode 7.3

---

script/helper/gen-compilation-db.js

Let's see if this helps atom/atom#16124 build without atom/apm#752.

Remove unnecessary "async"

---

lib/binding.js
src/binding.cpp
src/hub.h
src/message.cpp
src/message.h
src/thread.cpp
src/thread.h
src/worker/macos/macos_worker_platform.cpp
src/worker/macos/recent_file_cache.cpp
src/worker/macos/recent_file_cache.h
src/worker/worker_platform.h
src/worker/worker_thread.cpp
src/worker/worker_thread.h

Configure the maximum MacOS cache size and make it stricter about pruning entries when that maximum is reached.

Configurable MacOS cache

---

README.md
src/worker/macos/macos_worker_platform.cpp
src/worker/windows/windows_worker_platform.cpp

Handle cache size commands on Windows like we do on MacOS.

Configure the cache size on Windows

---

src/log.cpp
src/log.h
src/polling/polling_thread.cpp
src/worker/linux/linux_worker_platform.cpp
src/worker/linux/watch_registry.cpp
src/worker/macos/macos_worker_platform.cpp
src/worker/recent_file_cache.cpp
src/worker/windows/windows_worker_platform.cpp

Include a `Timer` class within the logging facility to capture simple performance data.

Capture performance data

---

test/events/symlink.test.js

This is mostly insurance for things to be aware of once we get to #112.
Fixes #19.

Unit tests for symlink edge cases

---

package.json

chore(package): update node-pre-gyp-github to version 1.4.1

---

package.json

chore(package): update electron-rebuild to version 1.8.2

---

package.json

chore(package): update eslint-plugin-promise to version 4.0.1

---

package-lock.json
package.json

It's been a while since I've touched this, so let's bring all of the dependencies up to date at once in one fell swoop and see what breaks. (Except for nan, which I'll do in its own PR because it might involve C++ tweaks.)

Bring dependencies up to date

---

package-lock.json
package.json

Upgrade Nan

---

package-lock.json
package.json

electron-rebuild@1.8.4

---

src/binding.cpp
src/hub.cpp

Update Set api usage to include context

Update Set api usage to include context
